services:
  homeflix-db:
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile.database
    container_name: homeflix-db
    volumes:
      - homeflix_data:/data
  homeflix-backend:
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile.backend
    ports:
      - "8000:8000"
    healthcheck:
      test: curl --fail http://localhost:8000/healthy || exit 1
      interval: 2m
      timeout: 10s
      start_period: 10s
      start_interval: 2s
    depends_on:
      homeflix-db:
        condition: service_completed_successfully
    container_name: homeflix-backend
    volumes:
      - homeflix_data:/data
  homeflix-frontend:
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile.frontend
    ports:
      - "8081:8501"
    depends_on:
      homeflix-backend:
        condition: service_healthy
    container_name: homeflix-frontend

volumes:
  homeflix_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${MOUNT_POINT}
