# Utilise une image de base Python officielle avec Python 3.9
FROM python:3.11-slim

# Définir le répertoire de travail dans le conteneur

# Copier les fichiers de dépendances

# Installer les dépendances

# Copier le reste du code de l'application

# Exposer le port sur lequel Streamlit fonctionne

# Commande pour démarrer l'application Streamlit
