FROM python:3.12.10-bookworm

WORKDIR /app

ADD backend/db_utils.py backend/main.py backend/recommender_chunk.py backend/requirements.txt .

# Installer DuckDB
RUN pip install -r requirements.txt


WORKDIR /

ENTRYPOINT ["fastapi", "run", "/app/main.py"]