FROM python:3.12.10-slim-bookworm

WORKDIR /app

ADD frontend/app.py frontend/utils.py frontend/requirements.txt .

# Installer DuckDB
RUN pip install -r requirements.txt

ENTRYPOINT ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0", "--server.headless=true"]
